# Generated by Django 5.0.1 on 2024-01-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sregno', models.IntegerField(unique=True)),
                ('sname', models.CharField(max_length=100)),
                ('sgender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('sage', models.IntegerField()),
                ('sdept', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics'), ('CF', 'Cyber Forensics'), ('MS', 'Mathematics')], max_length=50)),
                ('sfees', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('simage', models.ImageField(blank=True, null=True, upload_to='studphoto/')),
            ],
        ),
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub1', models.CharField(max_length=50, null=True)),
                ('mark1', models.IntegerField()),
                ('sub2', models.CharField(max_length=50, null=True)),
                ('mark2', models.IntegerField()),
                ('sub3', models.CharField(max_length=50, null=True)),
                ('mark3', models.IntegerField()),
                ('sub4', models.CharField(max_length=50, null=True)),
                ('mark4', models.IntegerField()),
                ('sub5', models.CharField(max_length=50, null=True)),
                ('mark5', models.IntegerField()),
                ('total', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentdetails')),
            ],
        ),
    ]
