# Generated by Django 5.0.1 on 2024-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marklist',
            old_name='teacher',
            new_name='user',
        ),
    ]
